{
    "data": [
        {
            "id": 27,
            "sysLanguage": "en",
            "activityType": 0,
            "informationType": 2,
            "title": "每日 每周任务",
            "imgUrl": "/img/6007/vendorlogo/082754186-34121-file_20260430082754176.webp",
            "state": 1,
            "sort": 44,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "",
            "pageType": 19,
            "pageId": 0,
            "startTime": 1776351467728,
            "creator": "Jayadmin",
            "createTime": 1775305145622,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777537676054,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": {
                "totalCanReceiveAmount": 0.0,
                "totalCanReceiveExp": 0,
                "pendingDayTask": [
                    {
                        "id": 35,
                        "taskLogo": "1",
                        "taskTitle": "Top-up betting rewards",
                        "taskType": 0,
                        "taskDetailType": 3,
                        "needRechargeAmount": 100.0000,
                        "minVipLevel": 0,
                        "taskDetail": {
                            "rechargeAmount": 200.0,
                            "betAmount": 1000.0,
                            "betCount": 0,
                            "minSingleBetAmount": 0.0,
                            "vendorCode": null,
                            "vendorName": null,
                            "categoryCode": null,
                            "categoryType": 0,
                            "gameCode": [],
                            "gameName": null,
                            "gameIds": null,
                            "invitedUserCount": 0
                        },
                        "currentTaskDetail": {
                            "rechargeAmount": 0.0000,
                            "betAmount": 0.0,
                            "betCount": 0,
                            "minSingleBetAmount": 0.0,
                            "vendorCode": null,
                            "vendorName": null,
                            "categoryCode": null,
                            "categoryType": 0,
                            "gameCode": null,
                            "gameName": null,
                            "gameIds": null,
                            "invitedUserCount": 0
                        },
                        "rewardAmount": 2.0000,
                        "codingMultiple": 1.0000,
                        "experienceScore": 10,
                        "endDate": "2036-04-15 00:00:00",
                        "sort": 11,
                        "dayWeekStatus": 0
                    }
                ],
                "pendingWeekTask": []
            },
            "newActivityState": 0
        },
        {
            "id": 22,
            "sysLanguage": "en",
            "activityType": 0,
            "informationType": 2,
            "title": "新版返佣",
            "imgUrl": "/img/6007/vendorlogo/023839042-33975-file_20260429143839034.webp",
            "state": 1,
            "sort": 48,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "",
            "pageType": 13,
            "pageId": 0,
            "startTime": 1776351463692,
            "creator": "Jayadmin",
            "createTime": 1775305145622,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777473520893,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": {
                "currentInviteCount": 0,
                "targetInviteCount": 1,
                "targetInviteRewardAmount": 50.0000
            },
            "newActivityState": 0
        },
        {
            "id": 16,
            "sysLanguage": "en",
            "activityType": 0,
            "informationType": 2,
            "title": "邀请轮盘",
            "imgUrl": "/img/6007/vendorlogo/024302403-33980-file_20260429144302394.webp",
            "state": 1,
            "sort": 3,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "",
            "pageType": 12,
            "pageId": 0,
            "startTime": 1776351454524,
            "creator": "Jayadmin",
            "createTime": 1775305145622,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777473784197,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": {
                "canWithdrawAmount": 0.0,
                "targetTotalPrizeAmount": 500.0000,
                "currentUserInvitedWheelAmount": 499.1900,
                "userInvitedWheelSpinCount": 0
            },
            "newActivityState": 0
        },
        {
            "id": 15,
            "sysLanguage": "en",
            "activityType": 0,
            "informationType": 2,
            "title": "礼品码",
            "imgUrl": "/img/6007/vendorlogo/024412842-33981-file_20260429144412833.webp",
            "state": 1,
            "sort": 55,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "",
            "pageType": 3,
            "pageId": 0,
            "startTime": 1776351451861,
            "creator": "Jayadmin",
            "createTime": 1775305145622,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777473854760,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": null,
            "newActivityState": 0
        },
        {
            "id": 29,
            "sysLanguage": "en",
            "activityType": 0,
            "informationType": 2,
            "title": "超级大奖",
            "imgUrl": "/img/6007/vendorlogo/024547159-33982-file_20260429144547151.webp",
            "state": 1,
            "sort": 0,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "",
            "pageType": 5,
            "pageId": 0,
            "startTime": 1776351448970,
            "creator": "System",
            "createTime": 1775740191679,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777473949569,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": {
                "totalRewardAmount": 0.0,
                "records": []
            },
            "newActivityState": 0
        },
        {
            "id": 23,
            "sysLanguage": "en",
            "activityType": 0,
            "informationType": 2,
            "title": "月卡 周卡",
            "imgUrl": "/img/6007/vendorlogo/023701804-33974-file_20260429143701790.webp",
            "state": 1,
            "sort": 48,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "",
            "pageType": 21,
            "pageId": 0,
            "startTime": 1776351008760,
            "creator": "Jayadmin",
            "createTime": 1775305145622,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777473423906,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": [
                {
                    "cardType": 0,
                    "isReceiveRwardToday": null,
                    "rewardDays": 7,
                    "dailyRewardAmount": 20.0000,
                    "expiredTime": 0,
                    "price": 5000.0000,
                    "enabled": true
                },
                {
                    "cardType": 1,
                    "isReceiveRwardToday": null,
                    "rewardDays": 30,
                    "dailyRewardAmount": 30.0000,
                    "expiredTime": 0,
                    "price": 20000.0000,
                    "enabled": true
                }
            ],
            "newActivityState": 0
        },
        {
            "id": 26,
            "sysLanguage": "en",
            "activityType": 0,
            "informationType": 2,
            "title": "游戏返利 3%",
            "imgUrl": "/img/6007/vendorlogo/024730541-33983-file_20260429144730529.webp",
            "state": 1,
            "sort": 30,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "",
            "pageType": 6,
            "pageId": 0,
            "startTime": 1776335153870,
            "creator": "Jayadmin",
            "createTime": 1775305145622,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777474052596,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": {
                "pendingWashCodeAmount": 0.00,
                "isOpenCodeWashing": true,
                "isFrontManualCodeWashing": true,
                "isSettleTheWashingAmount": true
            },
            "newActivityState": 0
        },
        {
            "id": 21,
            "sysLanguage": "en",
            "activityType": 0,
            "informationType": 2,
            "title": "VIP每月奖励",
            "imgUrl": "/img/6007/vendorlogo/023947624-33976-file_20260429143947616.webp",
            "state": 1,
            "sort": 49,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "",
            "pageType": 7,
            "pageId": 0,
            "startTime": 1776333466126,
            "creator": "Jayadmin",
            "createTime": 1775305145622,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777473589536,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": {
                "userVipLevel": 1,
                "totalUserCanReceiveAmount": 0.00,
                "canReceiveLevelAmount": 0.0,
                "canReceiveWeekAmount": 0.00,
                "canReceiveMonthAmount": 0.00,
                "currentRechargeAmount": 0.0000,
                "targetRechargeAmount": 400.00,
                "currentBetAmount": 166.5000,
                "targetBetAmount": 2500.00
            },
            "newActivityState": 0
        },
        {
            "id": 17,
            "sysLanguage": "en",
            "activityType": 0,
            "informationType": 2,
            "title": "充值轮盘",
            "imgUrl": "/img/6007/vendorlogo/024130829-33978-file_20260429144130820.webp",
            "state": 1,
            "sort": 50,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "",
            "pageType": 14,
            "pageId": 0,
            "startTime": 1776333403219,
            "creator": "Jayadmin",
            "createTime": 1775305145622,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777473692778,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": {
                "remainSpinCount": 0,
                "silverWheelTimes": 0,
                "goldWheelTimes": 0,
                "diamondWheelTimes": 0,
                "specialWheelTimes": 0,
                "currentRechargeAmount": 100.0000,
                "targetRechargeAmount": 500.0
            },
            "newActivityState": 0
        },
        {
            "id": 28,
            "sysLanguage": "en",
            "activityType": 0,
            "informationType": 2,
            "title": "每日签到",
            "imgUrl": "/img/6007/vendorlogo/023312744-33970-file_20260429143312732.webp",
            "state": 1,
            "sort": 49,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "",
            "pageType": 20,
            "pageId": 0,
            "startTime": 1776253910427,
            "creator": "Jayadmin",
            "createTime": 1775305145622,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777473195224,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": {
                "activityId": 13,
                "activityName": "DAILY CHECK-IN",
                "statisticsType": 0,
                "activityType": 1,
                "status": 1,
                "rewardDetail": {
                    "status": 1,
                    "dayIndex": 1,
                    "rechargeAmount": 100.0,
                    "rewardType": 0,
                    "rewardAmount": 2.0
                },
                "rechargeAmount": 0.0000,
                "currentCheckInDays": 1
            },
            "newActivityState": 0
        },
        {
            "id": 103183003,
            "sysLanguage": "en",
            "activityType": 1,
            "informationType": 1,
            "title": "FIRST DEPOSIT BONUS",
            "imgUrl": "https://pro-img.arsaaspub.com/6007/vendorlogo/081230286-38227-file_20260510081230278.webp",
            "state": 1,
            "sort": 11,
            "displayTarget": 0,
            "displayDetail": "",
            "content": "",
            "pageType": 0,
            "pageId": 0,
            "startTime": 1778400820517,
            "creator": "admin01",
            "createTime": 1776348723199,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1778400883876,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": null,
            "newActivityState": 1
        },
        {
            "id": 115161002,
            "sysLanguage": "en",
            "activityType": 1,
            "informationType": 1,
            "title": "Upgrade your VIP level  IPHONE 17",
            "imgUrl": "/img/6007/vendorlogo/022849550-34224-file_20260430142849447.webp",
            "state": 1,
            "sort": 0,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "",
            "pageType": 0,
            "pageId": 0,
            "startTime": 1777559355171,
            "creator": "admin01",
            "createTime": 1777559355171,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777559355172,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": null,
            "newActivityState": 0
        },
        {
            "id": 148906002,
            "sysLanguage": "en",
            "activityType": 1,
            "informationType": 1,
            "title": "DAILY SALARY SYSTEM 50,000",
            "imgUrl": "/img/6007/vendorlogo/022235774-33961-file_20260429142235765.webp",
            "state": 1,
            "sort": 25,
            "displayTarget": 0,
            "displayDetail": "",
            "content": "",
            "pageType": 0,
            "pageId": 0,
            "startTime": 1776790559415,
            "creator": "admin01",
            "createTime": 1776348528920,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777472587345,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": null,
            "newActivityState": 0
        },
        {
            "id": 149907002,
            "sysLanguage": "en",
            "activityType": 1,
            "informationType": 1,
            "title": "BIG AGENT REWARDS",
            "imgUrl": "/img/6007/vendorlogo/023002309-33966-file_20260429143002296.webp",
            "state": 1,
            "sort": 22,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "",
            "pageType": 0,
            "pageId": 0,
            "startTime": 1776774041444,
            "creator": "admin01",
            "createTime": 1776772489918,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777473020300,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": null,
            "newActivityState": 0
        },
        {
            "id": 114347002,
            "sysLanguage": "en",
            "activityType": 1,
            "informationType": 0,
            "title": "Benefits of Using ARWALLET",
            "imgUrl": "/img/6007/vendorlogo/023108788-33968-file_20260429143108779.webp",
            "state": 1,
            "sort": 0,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "https://t.me/ARWalletCLUB",
            "pageType": 0,
            "pageId": 0,
            "startTime": 1776772754356,
            "creator": "admin01",
            "createTime": 1776772754356,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777473071482,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": null,
            "newActivityState": 0
        },
        {
            "id": 153878004,
            "sysLanguage": "en",
            "activityType": 1,
            "informationType": 0,
            "title": "Follow our official WhatsApp channel",
            "imgUrl": "/img/6007/vendorlogo/022844904-33965-file_20260429142844889.webp",
            "state": 1,
            "sort": 58,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "https://whatsapp.com/channel/0029Vb6uYw31SWsuXXLmz33F",
            "pageType": 0,
            "pageId": 0,
            "startTime": 1776514879549,
            "creator": "admin00",
            "createTime": 1776510053887,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777472927777,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": null,
            "newActivityState": 0
        },
        {
            "id": 153417002,
            "sysLanguage": "en",
            "activityType": 1,
            "informationType": 0,
            "title": "INVITE",
            "imgUrl": "/img/6007/vendorlogo/022600048-33964-file_20260429142600038.webp",
            "state": 1,
            "sort": 0,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "/share?isTurntable=1",
            "pageType": 0,
            "pageId": 0,
            "startTime": 1776435653428,
            "creator": "admin01",
            "createTime": 1776435653428,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777472762616,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": null,
            "newActivityState": 0
        },
        {
            "id": 142722003,
            "sysLanguage": "en",
            "activityType": 1,
            "informationType": 1,
            "title": "AR Wallet Buy & Sell ARB 5% Bonus",
            "imgUrl": "/img/6007/vendorlogo/021940868-33958-file_20260429141940847.webp",
            "state": 1,
            "sort": 0,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "",
            "pageType": 1,
            "pageId": 0,
            "startTime": 1776254271675,
            "creator": "admin01",
            "createTime": 1776251742730,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777472384283,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": null,
            "newActivityState": 0
        },
        {
            "id": 131014003,
            "sysLanguage": "en",
            "activityType": 1,
            "informationType": 1,
            "title": "WINGO  WINNN BOUNS 100%",
            "imgUrl": "/img/6007/vendorlogo/021633989-33954-file_20260429141633860.webp",
            "state": 1,
            "sort": 21,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "",
            "pageType": 0,
            "pageId": 0,
            "startTime": 1776254224704,
            "creator": "admin01",
            "createTime": 1776251611023,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777472197722,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": null,
            "newActivityState": 0
        },
        {
            "id": 102369004,
            "sysLanguage": "en",
            "activityType": 1,
            "informationType": 0,
            "title": "FOLLOW OUR OFFICIAL Telegram BOT",
            "imgUrl": "/img/6007/vendorlogo/022042092-33959-file_20260429142042066.webp",
            "state": 1,
            "sort": 60,
            "displayTarget": 1,
            "displayDetail": "",
            "content": "https://t.me/GAME13L",
            "pageType": 16,
            "pageId": 0,
            "startTime": 1776254136255,
            "creator": "admin01",
            "createTime": 1776251882377,
            "lastUpdateMan": "admin01",
            "lastUpdateTime": 1777472445144,
            "activityInquiryType": 0,
            "rechargeAmount": 0.0,
            "conditionIndex": 0,
            "rechargeGiftPackId": 0,
            "buyMode": 0,
            "isShowTips": false,
            "tipsDetail": null,
            "newActivityState": 0
        }
    ],
    "code": 0,
    "msg": "Succeed",
    "msgCode": 0,
    "serverTime": 1778651473396
}